### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [logentries/lecli#26]
I have a leql query that works fine from the UI:

`where(/refresh/ and /request:(?P<request>[0-9]*.[0-9]*)s/) calculate(count) timeslice(24)`

It throws the following exception from lecli:

`Traceback (most recent call last):
  File ".virtualenvs/default/bin/lecli", line 11, in <module>
    sys.exit(cli())
  File ".virtualenvs/default/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File ".virtualenvs/default/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File ".virtualenvs/default/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".virtualenvs/default/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".virtualenvs/default/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/cli.py", line 115, in query
    query_api.post_query(logkeys, leql, date_from=datefrom, date_to=dateto)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 176, in post_query
    handle_response(response, progress_bar)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 76, in handle_response
    continue_request(response, progress_bar)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 90, in continue_request
    handle_response(new_response, progress_bar)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 72, in handle_response
    handle_response(next_response, progress_bar)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 72, in handle_response
    handle_response(next_response, progress_bar)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 72, in handle_response
    handle_response(next_response, progress_bar)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 68, in handle_response
    print_response(response)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 189, in print_response
    prettyprint_statistics(response)
  File ".virtualenvs/default/lib/python2.7/site-packages/lecli/query_api.py", line 224, in prettyprint_statistics
    stats_calc_key = data['statistics']['stats'].get(stats_key).keys()[0]
IndexError: list index out of range`

I'm running lecli v0.4.1 from a python v2.7.11 virtual environment.

**Comment by stopal-r7** [comment]
Hey @ruebrenda, I can reproduce this. Will be looking into it.
